#!/usr/bin/perl

# Copyright (C) 2010 Unsung hero
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# This is a filter for http://www.repubblica.it
# UNTESTED AS OF 2017
# NO MAINTAINER
# Instructions: 

use strict;

my ($link, $title, $descr);
my $count = 1;
my $found = 0;
my @lines = <>;

print '<?xml version="1.0"?>', "\n";
print '<!DOCTYPE rss PUBLIC "-//Netscape Communications//DTD RSS 0.91//EN"', "\n";
print ' "http://my.netscape.com/publish/formats/rss-0.91.dtd">', "\n";
print '<rss version="0.91">', "\n";
print '<channel>', "\n";
print '     <title>Repubblica - Ultimora</title>', "\n";
print '     <link>http://www.repubblica.it/news/ired/ultimora/altre_n.html</link>', "\n";
print '     <description>Ultime notizie</description>', "\n";
print '     <language>it</language>', "\n";

foreach ( @lines )
{
    s/&([aeiou])grave;/\1\`/gi;
    s/&([aeiou])acute;/\1\'/gi;

    if ( m/foglietti3\.gif/ )
    {
	$found = 1; 
	next;
    }

    if ( (m/href=\"(.*)\".*\<b\>(.*)\<\/b\>/) && $found == 1 )
    {
	$link = $1;
	$title = $2;
	$found++;
	next;
    }

    if ( (m/\<br\>(.*)\<\/td/) && $found == 2) 
    {
        $descr = $1;
	$found++;
	next;
    }

    if ( $found == 3 )
    {
	print '<item>', "\n";
	print '     <title>', $title, '</title>', "\n";
	print '     <link>http://www.repubblica.it/', $link, '</link>', "\n";
	print '     <description>',$descr, '</description>', "\n";
	print '</item>', "\n";

	last if ( $count == 20 );
	$count++;
	
	$found = 0;
    }
}

print '</channel>', "\n";
print '</rss>', "\n";
