#!/bin/bash

#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#                    Version 2, December 2004
#
# Copyright (C) 2017 Koz Ross <koz.ross@retro-freedom.nz>
#
# Everyone is permitted to copy and distribute verbatim or modified
# copies of this license document, and changing it is allowed as long
# as the name is changed.
#
#            DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE
#   TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION
#
#  0. You just DO WHAT THE FUCK YOU WANT TO.

# Script to convert content:encoded to description
# UNTESTED AS OF 2017
# NO MAINTAINER
# Instructions:

perl -e "my \$h='';while(<>){\$h.=\$_;};print \$h;" | grep -v "<description>" | grep -v "</description>" | sed 's/content:encoded/description/'
