#!/usr/bin/perl

# Filter for http://discountfan.de
# NO MAINTAINER
# NO LICENSE
# UNTESTED AS OF 2017
# Instructions:

use Data::Dumper;
use XML::LibXML;

my $contentblock  = 0;
my $base = 'http://www.discountfan.de';

foreach (<>) {
        chomp;
        if (/<!--  beginn inhalt blauer kasten2 -->/) {
                $contentblock = 1;
                next;
        }

        if ($contentblock && /<\/table>/) {
                last;
        }

        if ($contentblock == 1) {
                # headline
                while( /<td width="85%"><span class="subhead_blau2">([^<]+)<\/span><a href="(http:\/\/www\.discountfan\.de\/artikel\/[^\/]+\/[^\/]+\.php)"><span class="link_orangebig">([^<]+)<\/span><\/a><br>([^<]+)<?/g)
                {
                        my %item;
                        $item{'title'} = "$1 $3";
                        $item{'link'} = $2;
                        $item{'link'} =~ s/&/&amp;/g;
                        # article
                        $item{'content'} = $4;
                        $item{'content'} =~ s/&/&amp;/g;
                        unshift(@DB,\%item);
                }
        }
}

#############################################################
# Taken from sonataarctica feed gen script.
# Does not work on OpenBSD 3.5 (see http://kiza.kcore.de/journal/2004-11&item=2)

my $rssbase = $base;

# Create XML
my $nsrss = "http://purl.org/rss/1.0/";
my $nsrdf = "http://www.w3.org/1999/02/22-rdf-syntax-ns#";
my $nsdc = "http://purl.org/dc/elements/1.1/";

my($doc) = XML::LibXML::Document->new();
my($text);

my($root) = $doc->createElement('RDF');
$root->setNamespace($nsrss, '', 0);
$root->setNamespace($nsrdf, 'rdf', 1);
$root->setNamespace($nsdc, 'dc', 0);
$doc->setDocumentElement($root);
$doc->setEncoding("iso-8859-1");

my($channel) = $doc->createElement('channel');
$channel->setAttribute('rdf:about', "$rssbase");
$root->appendChild($channel);
$channel->appendTextChild('title', 'Discountfan news');
$channel->appendTextChild('link', "$rssbase");
$channel->appendTextChild('description', 'Discountfan.de news');

my($channelitems) = $doc->createElement('items');
$channel->appendChild($channelitems);
my($seqitems) = $doc->createElement('rdf:Seq');
$channelitems->appendChild($seqitems);

foreach (@DB) {
        my $rssurl = $_->{'link'};
        my($li) = $doc->createElement('rdf:li');
        $li->setAttribute('rdf:resource', "$rssurl");
        $seqitems->appendChild($li);

        my($rssitem) = $doc->createElement('item');
        $rssitem->setAttribute('rdf:about', "$rssurl");
        $root->appendChild($rssitem);
        $rssitem->appendTextChild('link', "$rssurl");
        $rssitem->appendTextChild('title', $_->{'title'});
#       $rssitem->appendTextChild('guid', $_->{'guid'});
        $rssitem->appendTextChild('description', $_->{'content'});

        $rssitem->appendTextChild('dc:date', $_->{'date'});
}

print $doc->serialize(1);

