#!/usr/bin/perl

# filter for www.heise.de (includes short item descriptions)

# NO MAINTAINER
# UNTESTED AS OF 2017
# NO LICENSE (claims GPL)
# Instructions:

my($contentblock) = 0;
my($what) = 0;
my(@news);

@lines = <>;

foreach (@lines) {
	chomp;
	if ($_ eq "<!-- Liste der Meldungen -->") {
		$contentblock = 1;
		next;
	}
	
	if ($_ eq "<!-- &Uuml;berblick -->") {
		last;
	}

	if ($contentblock == 1) {
		if (/<h3 class=\"anriss\">/) {
			# headline
			/<a href="(.*)">(.*)<\/a>/;
			$url = $1;
			$headline = $2;
			$headline =~ s/&/&amp;/g;
			push (@news,$headline);
			push (@news,$url);
		} elsif (/<p>/) {
			# article
			$desc = substr ($_, 3);
			$desc = (split(/</,$desc))[0];
			$desc =~ s/&/&amp;/g;
			push (@news,$desc);
		}
	}
}

print "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n".
	"<rdf:RDF\n".
	"xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n".
	"xmlns=\"http://my.netscape.com/rdf/simple/0.9/\">\n".
	"<channel>\n".
	"  <title>heise online news</title>\n".
	"  <link>http://www.heise.de/newsticker/</link>\n".
	"  <description>Nachrichten aus der Welt des Computers</description>\n".
	"</channel>\n";

$what = 0;
foreach (@news) {
	if ($_ eq "") {
		next;
	}
	if ($what == 0) {
		print "<item>\n<title>$_</title>\n";
		$what = 1;
		next;
	} elsif ($what == 1) {
		print "<link>http://www.heise.de$_</link>\n";
		$what = 2;
		next;
	} else {
		print "<description>$_</description>\n</item>\n";
		$what = 0;
	}
}

print "</rdf:RDF>\n";
