#!/usr/bin/perl

# Filter for http://www.heise.de/tp/. Apparently slow and dumps garbage.

# NO MAINTAINER
# UNTESTED AS OF 2017
# Instructions: 

my($contentblock) = 0;
my($what) = 0;
my(@news);

my %urls_heads = ();
my @lines = <>;

# get last article number
my $lastnr = `cat ~/.liferea/.telepolis3rss-last-nr 2>/dev/null`;
if ($lastnr =~ /^(\d+)$/) {
        $lastnr = $1;
} else {
	$lastnr = 0;
}

# gather links to article full texts
my $found = 0;
my $url;
foreach (@lines) {
	chomp;

	if($found) {
		s/<.*>$//g;
		$urls_heads{$url} = $_;
		$found=0;
	}	
	if(/^<p\s+class="inhalt-head"><a\s+href="([^"]+)"\s+class="link">/) {
		$url=$1;
		$found=1;
	}
}

# test for curl
`curl --help`;
if($? == 512) {
	# process collected links and get article texts
	foreach my $url (sort keys %urls_heads) {
		$url =~ /\/([^\/]*)\/[^\/]+\.html$/;
		if($lastnr < $1) {
			$lastnr = $1;
			@lines = `curl -s http://www.heise.de$url`;
			$contentblock = 0;
			$content = "";
			foreach(@lines) {
				if($_ =~ /<HEISETEXT>/) {
					$contentblock = 1;
					next;
				}
				
				last if($_ =~ /<\/HEISETEXT>/);	
				
				if($contentblock == 1) {
					$content .= $_;
				}
			}
			push(@news, $urls_heads{$url});
			push(@news, $url);
			push(@news, "<![CDATA[$content]]>");
		}
	}
} else {
	push(@news, "Filter script failed! curl not found!");
	push(@news, " ");
	push(@news, "This filter script uses curl to download websites. And it seems like curl is not installed!\n");
}

print "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?>\n".
	"<rdf:RDF\n".
	"xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"\n".
	"xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"\n".
	"xmlns=\"http://my.netscape.com/rdf/simple/0.9/\">\n".
	"<channel>\n".
	"  <title>Telepolis</title>\n".
	"  <link>http://www.telepolis.de/</link>\n".
	"  <description>Heise Online Magazin</description>\n".
	"</channel>\n";

$what = 0;
foreach (@news) {
	if ($_ eq "") {
		next;
	}
	if ($what == 0) {
		print "<item>\n<title>$_</title>\n";
		$what = 1;
		next;
	} elsif ($what == 1) {
		print "<link>http://www.heise.de$_</link>\n";
		$what = 2;
		next;
	} else {	
		print "<description>Sorry but your reader must support the content namespace!</description>\n";
		print "<content:encoded>$_</content:encoded>\n</item>\n";
		$what = 0;
	}
}

print "</rdf:RDF>\n";

`test -d ~/.liferea || mkdir ~/.liferea`;
`echo $lastnr > ~/.liferea/.telepolis3rss-last-nr 2>/dev/null`;


