#!/usr/bin/perl
                                                                                                                                               
# Xanga feed fixer, by Nathan Conrad.
# (c) 2004 Nathan Conrad
# ICQ #16106363 or AIM: t98502
# This is released with the BSD license, minus the advertising clause

# UNTESTED AS OF 2017
# MAINTAINER UNREACHABLE
# Instructions:

while(<>) {
    s@</channel><item>@<item>@;
    s@</rss>@</channel></rss>@;
    print $_;
}

