#!/bin/sh

echo "Machine information:"
uname -a
echo
echo
echo "System compiler:"
gcc -v
echo
echo
echo -n "libxml2 version: "
xml2-config --version
xml2-config --cflags
xml2-config --libs
echo
echo
echo "Snownews was linked against:"
ldd `which snownews`
